parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'

env:
  es6: true
  browser: true
  commonjs: true
  mocha: true

extends: 'airbnb'
parser: 'babel-eslint'

rules: {
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
}
