parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'

env:
  es6: true
  browser: true
  commonjs: true
  mocha: true

extends: 'airbnb'
parser: 'babel-eslint'

rules: {
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
  "import/prefer-default-export": off,
  "react/forbid-prop-types": off,
  "react/prefer-stateless-function": off,
  "no-plusplus": off,
  "no-param-reassign": off,
  "arrow-parens": off,
  "react/jsx-one-expression-per-line": off,
  "react/button-has-type": off,
  "class-methods-use-this": off,
  "no-restricted-syntax": off,

}
